name: Build and deploy Python app to Azure Web App - Development Slot

on:
  push:
    branches:
      - app-store  # Pas dit aan naar de juiste branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Checkout de code
      - uses: actions/checkout@v4

      # Stap 2: Python versie instellen
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Stap 3: Dependencies installeren vanuit /app/backend/requirements.txt
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r app/backend/requirements.txt  # Installeert alle dependencies

      # Stap 4: Artefact klaarmaken voor deployment
      - name: Prepare artifact for deployment
        run: |
          zip -r release.zip . -x "venv/*" "*.git*" ".*" "__pycache__/*"

      # Stap 5: Artefact uploaden
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'development'  # Dit is de naam van je GitHub Actions omgeving
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Stap 6: Artefact downloaden van de build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Stap 7: Artefact uitpakken
      - name: Unzip artifact
        run: unzip release.zip

      # Stap 8: Omgevingsvariabelen instellen
      - name: Set environment variables
        run: |
          echo "AZURE_APP_SERVICE=${{ secrets.AZURE_APP_SERVICE }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_ACCOUNT=${{ secrets.AZURE_STORAGE_ACCOUNT }}" >> $GITHUB_ENV
          echo "AZURE_SEARCH_SERVICE=${{ secrets.AZURE_SEARCH_SERVICE }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_SERVICE=${{ secrets.AZURE_OPENAI_SERVICE }}" >> $GITHUB_ENV
          echo "AZURE_KEY_VAULT_NAME=${{ secrets.AZURE_KEY_VAULT_NAME }}" >> $GITHUB_ENV

      # Stap 9: Deploy naar Azure Web App Slot
      - name: Deploy to Azure Web App Slot
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'app-backend-aq3pngevbp5ru'  # Naam van je App Service
          slot-name: 'ontwikkeling'              # Naam van je slot
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
